export const defaultMeridians = [
  { id: 'LU', name: 'Pulmón', english_name: 'Lung', chinese_pinyin: 'Feijing', pinyin_code: 'LU', element: 'Metal', yin_yang: 'Yin', total_points: 11, description: 'Regula el Qi respiratorio, la piel y los pasajes de agua. En lo emocional, se asocia con el procesamiento del duelo, la tristeza, la melancolía y la capacidad de dejar ir.' },
  { id: 'LI', name: 'Intestino Grueso', english_name: 'Large Intestine', chinese_pinyin: 'Dachangjing', pinyin_code: 'LI', element: 'Metal', yin_yang: 'Yang', total_points: 20, description: 'Encargado de la eliminación de desechos físicos y la absorción de líquidos. En lo emocional, rige la capacidad de soltar apegos, toxicidades y patrones obsoletos.' },
  { id: 'ST', name: 'Estómago', english_name: 'Stomach', chinese_pinyin: 'Weijing', pinyin_code: 'ST', element: 'Earth', yin_yang: 'Yang', total_points: 45, description: 'Recibe y digiere los alimentos físicos. En lo emocional, procesa los pensamientos y estímulos externos; su desequilibrio genera preocupación, obsesión y dificultad para asimilar la realidad.' },
  { id: 'SP', name: 'Bazo', english_name: 'Spleen', chinese_pinyin: 'Pijing', pinyin_code: 'SP', element: 'Earth', yin_yang: 'Yin', total_points: 21, description: 'Transforma y transporta los nutrientes, controla los músculos y la sangre. En lo emocional, rige el intelecto y la concentración; se afecta por el sobrepensamiento, la rumiación mental y la ansiedad.' },
  { id: 'HT', name: 'Corazón', english_name: 'Heart', chinese_pinyin: 'Xinjing', pinyin_code: 'HT', element: 'Fire', yin_yang: 'Yin', total_points: 9, description: 'Gobierna la sangre, los vasos y alberga el Shen (mente/espíritu). En lo emocional, es el centro de la alegría, el amor y la paz interior; su desequilibrio causa ansiedad, inquietud y falta de alegría.' },
  { id: 'SI', name: 'Intestino Delgado', english_name: 'Small Intestine', chinese_pinyin: 'Xiaochangjing', pinyin_code: 'SI', element: 'Fire', yin_yang: 'Yang', total_points: 19, description: 'Separa lo puro de lo turbio en la digestión. En lo emocional, ayuda a discernir entre lo que es útil y lo que daña, favoreciendo la claridad mental y la toma de decisiones sabias.' },
  { id: 'BL', name: 'Vejiga', english_name: 'Bladder', chinese_pinyin: 'Pangguangjing', pinyin_code: 'BL', element: 'Water', yin_yang: 'Yang', total_points: 67, description: 'Almacena y elimina la orina, y regula los órganos a través de los puntos Shu. En lo emocional, representa las reservas de adaptabilidad y resistencia ante el estrés y los miedos profundos.' },
  { id: 'KI', name: 'Riñón', english_name: 'Kidney', chinese_pinyin: 'Shenjing', pinyin_code: 'KI', element: 'Water', yin_yang: 'Yin', total_points: 27, description: 'Almacena la esencia vital (Jing), gobierna los huesos, el desarrollo y la reproducción. En lo emocional, es la raíz de la fuerza de voluntad y el coraje, y es vulnerable al miedo y la insecurity.' },
  { id: 'PC', name: 'Pericardio (Maestro Corazón)', english_name: 'Pericardium', chinese_pinyin: 'Xinbaojing', pinyin_code: 'PC', element: 'Fire', yin_yang: 'Yin', total_points: 9, description: 'Protege al Corazón del calor y patógenos externos. En lo emocional, actúa como un escudo emocional regulando la apertura afectiva, la vulnerabilidad y la intimidad en las relaciones.' },
  { id: 'TE', name: 'Triple Calentador', english_name: 'Triple Energizer', chinese_pinyin: 'Sanjiaojing', pinyin_code: 'SJ', element: 'Fire', yin_yang: 'Yang', total_points: 23, description: 'Coordina la distribución de fluidos y calor en el cuerpo (tres Jiao). En lo emocional, equilibra nuestra respuesta relacional y la adaptación al entorno, gestionando la autodefensa y el estrés térmico/emocional.' },
  { id: 'GB', name: 'Vesícula Biliar', english_name: 'Gallbladder', chinese_pinyin: 'Danjing', pinyin_code: 'GB', element: 'Wood', yin_yang: 'Yang', total_points: 44, description: 'Almacena y segrega la bilis. En lo emocional, gobierna la capacidad de decisión, el juicio asertivo, la planificación y el coraje para actuar; su bloqueo genera rabia reprimida, indecisión o frustración.' },
  { id: 'LR', name: 'Hígado', english_name: 'Liver', chinese_pinyin: 'Ganjing', pinyin_code: 'LR', element: 'Wood', yin_yang: 'Yin', total_points: 14, description: 'Asegura el libre flujo del Qi y almacena la sangre. En lo emocional, rige el crecimiento y la creatividad; su estancamiento produce ira, frustración, resentimiento, impaciencia y cambios de humor.' },
  { id: 'CV', name: 'Vaso Concepción', english_name: 'Conception Vessel', chinese_pinyin: 'Renmai', pinyin_code: 'REN', element: 'Ninguno', yin_yang: 'Yin', total_points: 24, description: 'Dirige y nutre la energía Yin de todo el cuerpo, regulando el útero y la reproducción. En lo emocional, rige la auto-nutrición, la receptividad, la compasión hacia uno mismo y el autocuidado profundo.' },
  { id: 'GV', name: 'Vaso Gobernador (Du Mai)', english_name: 'Governing Vessel', chinese_pinyin: 'Dumai', pinyin_code: 'DU', element: 'Ninguno', yin_yang: 'Yang', total_points: 28, description: 'Dirige y nutre la energía Yang, controlando la columna y el cerebro. En lo emocional, representa la estabilidad, la fuerza interior, la autoestima, la capacidad de erguirse con dignidad y avanzar con dirección.' },
  { id: 'EX', name: 'Puntos Extra', english_name: 'Extra Points', chinese_pinyin: 'Waiqi', pinyin_code: 'EX', element: 'Ninguno', yin_yang: 'Ninguno', total_points: 0, description: 'Puntos especiales fuera de los meridianos principales. Actúan de forma focalizada regulando dolencias agudas y aportando calma inmediata a nivel mental y físico.' },
];

